/*
 * Copyright (C) 2026 Neeme Praks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.nemecec.protobuf.javamin.codegen;

import com.google.protobuf.DescriptorProtos.EnumDescriptorProto;
import com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto;

/**
 * Generates a Java source file for one proto {@code enum}. The generated type
 * is a Java {@code enum} with a {@code value} field carrying the proto integer
 * and a {@link #forNumber(int)} static factory used by message decoders.
 */
final class EnumWriter {

  private final String javaPackage;

  EnumWriter(String javaPackage) {
    this.javaPackage = javaPackage;
  }

  String write(EnumDescriptorProto e) {
    StringBuilder sb = new StringBuilder();
    sb.append("// Generated by protobuf-javamin. DO NOT EDIT.\n");
    if (!javaPackage.isEmpty()) {
      sb.append("package ").append(javaPackage).append(";\n\n");
    }

    sb.append("public enum ").append(e.getName()).append(" {\n");
    int last = e.getValueCount() - 1;
    for (int i = 0; i <= last; i++) {
      EnumValueDescriptorProto v = e.getValue(i);
      sb.append("  ").append(v.getName()).append("(").append(v.getNumber()).append(")");
      sb.append(i == last ? ";\n\n" : ",\n");
    }

    // Mirror javalite: emit a per-entry static int constant alongside the enum
    // entries. Generated and hand-written wrapper code that wants the wire value
    // without going through `.getNumber()` references these (e.g., when used as
    // an annotation argument or inline initialiser).
    for (EnumValueDescriptorProto v : e.getValueList()) {
      sb.append("  public static final int ").append(v.getName()).append("_VALUE = ")
          .append(v.getNumber()).append(";\n");
    }
    sb.append("\n");

    sb.append("  private final int value;\n\n");
    sb.append("  ").append(e.getName()).append("(int value) { this.value = value; }\n\n");

    sb.append("  public int getNumber() { return value; }\n\n");

    sb.append("  /** Reverse lookup. Returns {@code null} for unknown numbers — callers\n");
    sb.append("   *  treat unknown enum values as missing on the wire (proto2 semantics). */\n");
    sb.append("  public static ").append(e.getName()).append(" forNumber(int value) {\n");
    sb.append("    switch (value) {\n");
    for (EnumValueDescriptorProto v : e.getValueList()) {
      sb.append("      case ").append(v.getNumber()).append(": return ").append(v.getName()).append(";\n");
    }
    sb.append("      default: return null;\n");
    sb.append("    }\n");
    sb.append("  }\n");
    sb.append("}\n");
    return sb.toString();
  }
}
