/*
 * Copyright (C) 2026 Neeme Praks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.nemecec.protobuf.javamin.codegen;

import com.google.protobuf.DescriptorProtos.DescriptorProto;
import com.google.protobuf.DescriptorProtos.EnumDescriptorProto;
import com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto;
import com.google.protobuf.DescriptorProtos.FieldDescriptorProto;
import com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Label;
import com.google.protobuf.DescriptorProtos.OneofDescriptorProto;
import dev.nemecec.protobuf.javamin.codegen.JavaGen.FieldKind;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Generates the Java source for one proto message (and recursively for nested
 * messages and enums). The output is stitched together by {@link JavaGen}.
 *
 * <p>One {@code MessageWriter} instance handles all messages in one Java file:
 * the same instance is reused recursively for nested types because they share
 * the file's package and import set.
 */
final class MessageWriter {

  private final TypeRegistry registry;
  private final String javaPackage;

  MessageWriter(TypeRegistry registry, String javaPackage) {
    this.registry = registry;
    this.javaPackage = javaPackage;
  }

  String write(DescriptorProto top) {
    StringBuilder sb = new StringBuilder();
    sb.append("// Generated by protobuf-javamin. DO NOT EDIT.\n");
    if (!javaPackage.isEmpty()) sb.append("package ").append(javaPackage).append(";\n\n");

    // We reference these on every generated file. Java warns on unused imports
    // but tolerates them, so unconditional imports keep the codegen simple.
    sb.append("import java.io.IOException;\n");
    sb.append("import java.io.InputStream;\n");
    sb.append("import java.util.ArrayList;\n");
    sb.append("import java.util.Collections;\n");
    sb.append("import java.util.List;\n");
    sb.append("import dev.nemecec.protobuf.javamin.AbstractMessageLite;\n");
    sb.append("import dev.nemecec.protobuf.javamin.ByteString;\n");
    sb.append("import dev.nemecec.protobuf.javamin.CodedInputStream;\n");
    sb.append("import dev.nemecec.protobuf.javamin.CodedOutputStream;\n");
    sb.append("import dev.nemecec.protobuf.javamin.Internal;\n");
    sb.append("import dev.nemecec.protobuf.javamin.InvalidProtocolBufferException;\n");
    sb.append("import dev.nemecec.protobuf.javamin.MessageLite;\n");
    sb.append("import dev.nemecec.protobuf.javamin.UninitializedMessageException;\n");
    sb.append("import dev.nemecec.protobuf.javamin.WireFormat;\n");
    sb.append("\n");

    writeMessage(sb, top, "");
    return sb.toString();
  }

  // --- one message --------------------------------------------------------
  // The {@code outerJavaName} is the dot-joined Java name of the enclosing
  // message(s), used to reference {@code this}-typed nested fields without
  // package qualification. Empty for top-level messages.

  private void writeMessage(StringBuilder sb, DescriptorProto m, String outerJavaName) {
    boolean isNested = !outerJavaName.isEmpty();
    String name = m.getName();
    String selfQualified = isNested ? outerJavaName + "." + name : name;
    String indent = isNested ? "  " : "";
    String inner = indent + "  ";

    sb.append(indent).append("public ");
    if (isNested) sb.append("static ");
    sb.append("final class ").append(name)
        .append(" extends AbstractMessageLite<").append(selfQualified)
        .append(", ").append(selfQualified).append(".Builder> {\n\n");

    // Private no-arg constructor — instances are produced via Builder.buildPartial().
    sb.append(inner).append("private ").append(name).append("() {}\n\n");

    // Default instance — used by getDefaultInstance().
    sb.append(inner).append("private static final ").append(selfQualified).append(" DEFAULT_INSTANCE = new ").append(name).append("();\n");
    sb.append(inner).append("public static ").append(selfQualified).append(" getDefaultInstance() { return DEFAULT_INSTANCE; }\n\n");

    // Field declarations.
    for (FieldDescriptorProto f : m.getFieldList()) {
      writeFieldDeclarations(sb, f, inner);
    }
    sb.append("\n");

    // Public getters / hassers on the message.
    for (FieldDescriptorProto f : m.getFieldList()) {
      writeMessageAccessors(sb, f, inner);
    }

    // Per-oneof case accessor on the message.
    Map<Integer, List<FieldDescriptorProto>> oneofs = oneofGroups(m);
    for (Map.Entry<Integer, List<FieldDescriptorProto>> entry : oneofs.entrySet()) {
      OneofDescriptorProto oneof = m.getOneofDecl(entry.getKey());
      writeOneofCaseGetter(sb, oneof, entry.getValue(), inner);
    }

    // isInitialized.
    sb.append(inner).append("@Override\n");
    sb.append(inner).append("public boolean isInitialized() {\n");
    for (FieldDescriptorProto f : m.getFieldList()) {
      if (f.getLabel() == Label.LABEL_REQUIRED) {
        sb.append(inner).append("  if (!").append(hasFlagName(f)).append(") return false;\n");
      }
      // For required message fields we'd also need to recurse into their isInitialized();
      // proto2 spec allows that, but it isn't a feature we currently emit.
    }
    sb.append(inner).append("  return true;\n");
    sb.append(inner).append("}\n\n");

    // writeTo.
    sb.append(inner).append("@Override\n");
    sb.append(inner).append("public void writeTo(CodedOutputStream output) throws IOException {\n");
    for (FieldDescriptorProto f : m.getFieldList()) {
      writeFieldWrite(sb, f, inner + "  ");
    }
    sb.append(inner).append("}\n\n");

    // getSerializedSize.
    sb.append(inner).append("@Override\n");
    sb.append(inner).append("public int getSerializedSize() {\n");
    sb.append(inner).append("  int size = 0;\n");
    for (FieldDescriptorProto f : m.getFieldList()) {
      writeFieldSize(sb, f, inner + "  ");
    }
    sb.append(inner).append("  return size;\n");
    sb.append(inner).append("}\n\n");

    // equals / hashCode — field-by-field, allocation-free. Matches what
    // protobuf-javalite emits: only set (has-flag true) optional fields and
    // non-empty repeated fields contribute to the hash, so an unset field
    // and a field set to its type-default still compare equal across instances.
    sb.append(inner).append("@Override\n");
    sb.append(inner).append("public boolean equals(Object obj) {\n");
    sb.append(inner).append("  if (this == obj) return true;\n");
    sb.append(inner).append("  if (!(obj instanceof ").append(name).append(")) return false;\n");
    sb.append(inner).append("  ").append(name).append(" other = (").append(name).append(") obj;\n");
    for (FieldDescriptorProto f : m.getFieldList()) {
      writeFieldEquals(sb, f, inner + "  ");
    }
    sb.append(inner).append("  return true;\n");
    sb.append(inner).append("}\n\n");

    sb.append(inner).append("@Override\n");
    sb.append(inner).append("public int hashCode() {\n");
    sb.append(inner).append("  int hash = 1;\n");
    for (FieldDescriptorProto f : m.getFieldList()) {
      writeFieldHash(sb, f, inner + "  ");
    }
    sb.append(inner).append("  return hash;\n");
    sb.append(inner).append("}\n\n");

    // toString — emit only the fields that are actually set, comma-separated,
    // suitable for log lines and test failure output. Strings are quoted; enums
    // are rendered as their typed name; embedded messages recurse via their own
    // toString. Repeated fields delegate to List.toString (which calls toString
    // on each element).
    sb.append(inner).append("@Override\n");
    sb.append(inner).append("public String toString() {\n");
    sb.append(inner).append("  StringBuilder sb = new StringBuilder().append(\"").append(name).append("{\");\n");
    sb.append(inner).append("  String sep = \"\";\n");
    for (FieldDescriptorProto f : m.getFieldList()) {
      writeFieldToString(sb, f, inner + "  ");
    }
    sb.append(inner).append("  return sb.append(\"}\").toString();\n");
    sb.append(inner).append("}\n\n");

    // Static parse helpers + newBuilder.
    sb.append(inner).append("public static ").append(selfQualified)
        .append(" parseFrom(byte[] data) throws InvalidProtocolBufferException {\n");
    sb.append(inner).append("  return AbstractMessageLite.parseFrom(newBuilder(), data);\n");
    sb.append(inner).append("}\n\n");

    sb.append(inner).append("public static ").append(selfQualified)
        .append(" parseFrom(InputStream input) throws IOException {\n");
    sb.append(inner).append("  return AbstractMessageLite.parseFrom(newBuilder(), input);\n");
    sb.append(inner).append("}\n\n");

    sb.append(inner).append("public static ").append(selfQualified)
        .append(" parseDelimitedFrom(InputStream input) throws IOException {\n");
    sb.append(inner).append("  return AbstractMessageLite.parseDelimitedFrom(newBuilder(), input);\n");
    sb.append(inner).append("}\n\n");

    sb.append(inner).append("public static Builder newBuilder() { return new Builder(); }\n\n");

    // Builder.
    writeBuilder(sb, m, selfQualified, inner);

    // Nested types.
    for (DescriptorProto nested : m.getNestedTypeList()) {
      writeMessage(sb, nested, selfQualified);
    }
    for (EnumDescriptorProto nestedEnum : m.getEnumTypeList()) {
      writeNestedEnum(sb, nestedEnum, inner);
    }
    // One Case enum per oneof, alongside other nested types.
    for (Map.Entry<Integer, List<FieldDescriptorProto>> entry : oneofs.entrySet()) {
      OneofDescriptorProto oneof = m.getOneofDecl(entry.getKey());
      writeOneofCaseEnum(sb, oneof, entry.getValue(), inner);
    }

    sb.append(indent).append("}\n");
  }

  // --- builder ------------------------------------------------------------

  private void writeBuilder(StringBuilder sb, DescriptorProto m, String selfQualified, String inner) {
    String binner = inner + "  ";
    sb.append(inner).append("public static final class Builder implements MessageLite.Builder<")
        .append(selfQualified).append(", Builder> {\n\n");

    // Mirror fields.
    for (FieldDescriptorProto f : m.getFieldList()) {
      writeFieldDeclarations(sb, f, binner);
    }
    sb.append("\n");

    // Setters / hassers / clearers.
    Map<Integer, List<FieldDescriptorProto>> oneofs = oneofGroups(m);
    for (FieldDescriptorProto f : m.getFieldList()) {
      List<FieldDescriptorProto> siblings =
          f.hasOneofIndex() ? oneofs.get(f.getOneofIndex()) : null;
      writeBuilderAccessors(sb, f, binner, siblings);
    }

    // Per-oneof case accessor on the builder.
    for (Map.Entry<Integer, List<FieldDescriptorProto>> entry : oneofs.entrySet()) {
      OneofDescriptorProto oneof = m.getOneofDecl(entry.getKey());
      writeOneofCaseGetter(sb, oneof, entry.getValue(), binner);
    }

    // build / buildPartial.
    sb.append(binner).append("@Override\n");
    sb.append(binner).append("public ").append(selfQualified).append(" build() {\n");
    sb.append(binner).append("  ").append(selfQualified).append(" m = buildPartial();\n");
    sb.append(binner).append("  if (!m.isInitialized()) throw new UninitializedMessageException(m);\n");
    sb.append(binner).append("  return m;\n");
    sb.append(binner).append("}\n\n");

    sb.append(binner).append("@Override\n");
    sb.append(binner).append("public ").append(selfQualified).append(" buildPartial() {\n");
    sb.append(binner).append("  ").append(selfQualified).append(" m = new ").append(selfQualified).append("();\n");
    for (FieldDescriptorProto f : m.getFieldList()) {
      if (f.getLabel() == Label.LABEL_REPEATED) {
        // Freeze the list: assign as Collections.unmodifiableList wrapping the current ArrayList,
        // or empty list if untouched. The unmodifiability guards against accidental post-build mutation.
        sb.append(binner).append("  m.").append(fieldName(f)).append(" = ").append(fieldName(f))
            .append(".isEmpty() ? Internal.<").append(repeatedStorageType(f)).append(">emptyList() : Collections.unmodifiableList(")
            .append(fieldName(f)).append(");\n");
      } else {
        sb.append(binner).append("  m.").append(hasFlagName(f)).append(" = ").append(hasFlagName(f)).append(";\n");
        sb.append(binner).append("  m.").append(fieldName(f)).append(" = ").append(fieldName(f)).append(";\n");
      }
    }
    sb.append(binner).append("  return m;\n");
    sb.append(binner).append("}\n\n");

    // mergeFrom(CodedInputStream).
    sb.append(binner).append("@Override\n");
    sb.append(binner).append("public Builder mergeFrom(CodedInputStream input) throws IOException {\n");
    sb.append(binner).append("  int tag;\n");
    sb.append(binner).append("  while ((tag = input.readTag()) != 0) {\n");
    sb.append(binner).append("    switch (tag) {\n");
    for (FieldDescriptorProto f : m.getFieldList()) {
      writeFieldRead(sb, f, binner + "      ");
    }
    sb.append(binner).append("      default:\n");
    sb.append(binner).append("        if (!input.skipField(tag)) return this;\n");
    sb.append(binner).append("        break;\n");
    sb.append(binner).append("    }\n");
    sb.append(binner).append("  }\n");
    sb.append(binner).append("  return this;\n");
    sb.append(binner).append("}\n");

    sb.append(inner).append("}\n\n");
  }

  // --- nested enum --------------------------------------------------------

  // --- oneof support ------------------------------------------------------

  /** Group a message's fields by their oneof index. Fields not in any oneof
   *  are skipped. Synthetic proto3-optional oneofs would also be skipped, but
   *  we don't support proto3 anyway. */
  private static Map<Integer, List<FieldDescriptorProto>> oneofGroups(DescriptorProto m) {
    Map<Integer, List<FieldDescriptorProto>> out = new LinkedHashMap<>();
    for (FieldDescriptorProto f : m.getFieldList()) {
      if (!f.hasOneofIndex()) continue;
      out.computeIfAbsent(f.getOneofIndex(), k -> new ArrayList<>()).add(f);
    }
    return out;
  }

  /** {@code public XxxCase getXxxCase()} on the message and on the builder.
   *  Reads has-flags in declaration order; first set wins. Setters of oneof
   *  members on the builder clear sibling has-flags so at most one is set at
   *  a time, but the read still tolerates inconsistent state. */
  private void writeOneofCaseGetter(StringBuilder sb, OneofDescriptorProto oneof,
                                    List<FieldDescriptorProto> members, String indent) {
    String caseEnum = caseEnumName(oneof);
    String getterName = "get" + capitalize(oneof.getName()) + "Case";
    sb.append(indent).append("public ").append(caseEnum).append(" ").append(getterName).append("() {\n");
    for (FieldDescriptorProto member : members) {
      sb.append(indent).append("  if (").append(hasFlagName(member)).append(") return ").append(caseEnum)
          .append(".").append(oneofConstName(member)).append(";\n");
    }
    sb.append(indent).append("  return ").append(caseEnum).append(".").append(notSetConstName(oneof)).append(";\n");
    sb.append(indent).append("}\n");
  }

  /** {@code public enum XxxCase { FIELD1(N), FIELD2(M), XXX_NOT_SET(0); ... }}
   *  Emitted as a nested type alongside other nested classes. Numeric values
   *  match the proto field number per javalite convention. */
  private void writeOneofCaseEnum(StringBuilder sb, OneofDescriptorProto oneof,
                                  List<FieldDescriptorProto> members, String indent) {
    String name = caseEnumName(oneof);
    sb.append(indent).append("public enum ").append(name).append(" {\n");
    for (FieldDescriptorProto member : members) {
      sb.append(indent).append("  ").append(oneofConstName(member)).append("(").append(member.getNumber()).append("),\n");
    }
    sb.append(indent).append("  ").append(notSetConstName(oneof)).append("(0);\n");
    sb.append(indent).append("  private final int value;\n");
    sb.append(indent).append("  ").append(name).append("(int value) { this.value = value; }\n");
    sb.append(indent).append("  public int getNumber() { return value; }\n");
    sb.append(indent).append("  public static ").append(name).append(" forNumber(int value) {\n");
    sb.append(indent).append("    switch (value) {\n");
    for (FieldDescriptorProto member : members) {
      sb.append(indent).append("      case ").append(member.getNumber()).append(": return ")
          .append(oneofConstName(member)).append(";\n");
    }
    sb.append(indent).append("      case 0: return ").append(notSetConstName(oneof)).append(";\n");
    sb.append(indent).append("      default: return null;\n");
    sb.append(indent).append("    }\n");
    sb.append(indent).append("  }\n");
    sb.append(indent).append("}\n\n");
  }

  /** Snippet emitted at the start of a oneof-member setter: clear all sibling
   *  has-flags so at most one variant is "present" at a time. */
  private static void writeOneofSiblingClears(StringBuilder sb, FieldDescriptorProto self,
                                              List<FieldDescriptorProto> siblings) {
    for (FieldDescriptorProto sib : siblings) {
      if (sib == self) continue;
      sb.append(hasFlagName(sib)).append(" = false; ");
    }
  }

  private static String caseEnumName(OneofDescriptorProto oneof) {
    return capitalize(oneof.getName()) + "Case";
  }

  private static String oneofConstName(FieldDescriptorProto member) {
    return member.getName().toUpperCase(Locale.ROOT);
  }

  private static String notSetConstName(OneofDescriptorProto oneof) {
    return oneof.getName().toUpperCase(Locale.ROOT) + "_NOT_SET";
  }

  private void writeNestedEnum(StringBuilder sb, EnumDescriptorProto e, String indent) {
    sb.append(indent).append("public enum ").append(e.getName()).append(" {\n");
    int last = e.getValueCount() - 1;
    for (int i = 0; i <= last; i++) {
      EnumValueDescriptorProto v = e.getValue(i);
      sb.append(indent).append("  ").append(v.getName()).append("(").append(v.getNumber()).append(")");
      sb.append(i == last ? ";\n\n" : ",\n");
    }
    for (EnumValueDescriptorProto v : e.getValueList()) {
      sb.append(indent).append("  public static final int ").append(v.getName())
          .append("_VALUE = ").append(v.getNumber()).append(";\n");
    }
    sb.append(indent).append("  private final int value;\n");
    sb.append(indent).append("  ").append(e.getName()).append("(int value) { this.value = value; }\n");
    sb.append(indent).append("  public int getNumber() { return value; }\n");
    sb.append(indent).append("  public static ").append(e.getName()).append(" forNumber(int value) {\n");
    sb.append(indent).append("    switch (value) {\n");
    for (EnumValueDescriptorProto v : e.getValueList()) {
      sb.append(indent).append("      case ").append(v.getNumber()).append(": return ").append(v.getName()).append(";\n");
    }
    sb.append(indent).append("      default: return null;\n");
    sb.append(indent).append("    }\n");
    sb.append(indent).append("  }\n");
    sb.append(indent).append("}\n\n");
  }

  // --- field-level emission ----------------------------------------------

  private void writeFieldDeclarations(StringBuilder sb, FieldDescriptorProto f, String indent) {
    if (f.getLabel() == Label.LABEL_REPEATED) {
      sb.append(indent).append("private List<").append(repeatedStorageType(f)).append("> ")
          .append(fieldName(f)).append(" = Internal.emptyList();\n");
    } else {
      sb.append(indent).append("private boolean ").append(hasFlagName(f)).append(";\n");
      sb.append(indent).append("private ").append(primJavaType(f)).append(" ")
          .append(fieldName(f)).append(initializerSuffix(f)).append(";\n");
    }
  }

  private void writeMessageAccessors(StringBuilder sb, FieldDescriptorProto f, String indent) {
    String name = f.getName();
    String capName = capitalize(name);
    if (f.getLabel() == Label.LABEL_REPEATED) {
      writeRepeatedReadOnlyAccessors(sb, f, indent, capName);
    } else {
      sb.append(indent).append("public boolean has").append(capName).append("() { return ")
          .append(hasFlagName(f)).append("; }\n");
      if (FieldKind.from(f.getType()) == FieldKind.ENUM) {
        sb.append(indent).append("public ").append(boxedJavaType(f)).append(" get").append(capName)
            .append("() { return ").append(boxedJavaType(f)).append(".forNumber(")
            .append(fieldName(f)).append("); }\n");
        sb.append(indent).append("public int get").append(capName).append("Value() { return ")
            .append(fieldName(f)).append("; }\n");
      } else {
        sb.append(indent).append("public ").append(primJavaType(f)).append(" get").append(capName)
            .append("() { return ").append(fieldName(f)).append("; }\n");
      }
    }
  }

  /** Read-only accessors shared by message and builder for a repeated field. */
  private void writeRepeatedReadOnlyAccessors(StringBuilder sb, FieldDescriptorProto f, String indent, String capName) {
    String storage = repeatedStorageType(f);
    String fld = fieldName(f);
    boolean isEnum = FieldKind.from(f.getType()) == FieldKind.ENUM;
    String enumApi = isEnum ? boxedJavaType(f) : null;

    if (isEnum) {
      // Expose both the typed enum and the raw int views (the int view matches
      // what the wire format actually carries; the enum view is the user-facing API).
      sb.append(indent).append("public List<Integer> get").append(capName)
          .append("ValueList() { return ").append(fld).append("; }\n");
    }
    sb.append(indent).append("public List<").append(isEnum ? enumApi : storage).append("> get")
        .append(capName).append("List() { ");
    if (isEnum) {
      sb.append("List<").append(enumApi).append("> out = new ArrayList<").append(enumApi).append(">(")
          .append(fld).append(".size()); for (Integer v : ").append(fld).append(") out.add(")
          .append(enumApi).append(".forNumber(v)); return out;");
    } else {
      sb.append("return ").append(fld).append(";");
    }
    sb.append(" }\n");

    sb.append(indent).append("public int get").append(capName).append("Count() { return ")
        .append(fld).append(".size(); }\n");

    if (isEnum) {
      sb.append(indent).append("public ").append(enumApi).append(" get").append(capName)
          .append("(int index) { return ").append(enumApi).append(".forNumber(")
          .append(fld).append(".get(index)); }\n");
      sb.append(indent).append("public int get").append(capName)
          .append("Value(int index) { return ").append(fld).append(".get(index); }\n");
    } else {
      sb.append(indent).append("public ").append(storage).append(" get").append(capName)
          .append("(int index) { return ").append(fld).append(".get(index); }\n");
    }
  }

  /** Repeated-field setters/adders/clearers — only on the Builder side. */
  private void writeRepeatedMutators(StringBuilder sb, FieldDescriptorProto f, String indent, String capName) {
    String storage = repeatedStorageType(f);
    String fld = fieldName(f);
    boolean isEnum = FieldKind.from(f.getType()) == FieldKind.ENUM;
    String enumApi = isEnum ? boxedJavaType(f) : null;

    if (isEnum) {
      // Typed-enum setters: stash value.getNumber() in the int-backed list.
      sb.append(indent).append("public Builder set").append(capName).append("(int index, ").append(enumApi)
          .append(" value) { if (value == null) throw new NullPointerException(); ensure").append(capName)
          .append("Mutable(); ").append(fld).append(".set(index, value.getNumber()); return this; }\n");
      sb.append(indent).append("public Builder add").append(capName).append("(").append(enumApi)
          .append(" value) { if (value == null) throw new NullPointerException(); ensure").append(capName)
          .append("Mutable(); ").append(fld).append(".add(value.getNumber()); return this; }\n");
      sb.append(indent).append("public Builder addAll").append(capName).append("(Iterable<? extends ")
          .append(enumApi).append("> values) { ensure").append(capName).append("Mutable(); for (")
          .append(enumApi).append(" v : values) ").append(fld).append(".add(v.getNumber()); return this; }\n");
      // Int-backed setters mirror the Value-suffix scalar enum API.
      sb.append(indent).append("public Builder set").append(capName)
          .append("Value(int index, int value) { ensure").append(capName).append("Mutable(); ")
          .append(fld).append(".set(index, value); return this; }\n");
      sb.append(indent).append("public Builder add").append(capName)
          .append("Value(int value) { ensure").append(capName).append("Mutable(); ")
          .append(fld).append(".add(value); return this; }\n");
    } else {
      sb.append(indent).append("public Builder set").append(capName).append("(int index, ").append(storage)
          .append(" value) { ensure").append(capName).append("Mutable(); ").append(fld)
          .append(".set(index, value); return this; }\n");
      sb.append(indent).append("public Builder add").append(capName).append("(").append(storage)
          .append(" value) { ensure").append(capName).append("Mutable(); ").append(fld)
          .append(".add(value); return this; }\n");
      sb.append(indent).append("public Builder addAll").append(capName).append("(Iterable<? extends ")
          .append(storage).append("> values) { ensure").append(capName).append("Mutable(); for (")
          .append(storage).append(" v : values) ").append(fld).append(".add(v); return this; }\n");
    }
    sb.append(indent).append("public Builder clear").append(capName).append("() { ").append(fld)
        .append(" = Internal.emptyList(); return this; }\n");
    sb.append(indent).append("private void ensure").append(capName).append("Mutable() {\n");
    sb.append(indent).append("  if (!(").append(fld).append(" instanceof ArrayList)) ")
        .append(fld).append(" = new ArrayList<").append(storage).append(">(").append(fld).append(");\n");
    sb.append(indent).append("}\n");
  }

  private void writeBuilderAccessors(StringBuilder sb, FieldDescriptorProto f, String indent,
                                     List<FieldDescriptorProto> oneofSiblings) {
    String name = f.getName();
    String capName = capitalize(name);
    if (f.getLabel() == Label.LABEL_REPEATED) {
      writeRepeatedReadOnlyAccessors(sb, f, indent, capName);
      writeRepeatedMutators(sb, f, indent, capName);
    } else {
      FieldKind k = FieldKind.from(f.getType());
      sb.append(indent).append("public boolean has").append(capName).append("() { return ")
          .append(hasFlagName(f)).append("; }\n");
      if (k == FieldKind.ENUM) {
        sb.append(indent).append("public ").append(boxedJavaType(f)).append(" get").append(capName)
            .append("() { return ").append(boxedJavaType(f)).append(".forNumber(")
            .append(fieldName(f)).append("); }\n");
        sb.append(indent).append("public int get").append(capName).append("Value() { return ")
            .append(fieldName(f)).append("; }\n");
        sb.append(indent).append("public Builder set").append(capName).append("(").append(boxedJavaType(f))
            .append(" value) { if (value == null) throw new NullPointerException(); ");
        if (oneofSiblings != null) writeOneofSiblingClears(sb, f, oneofSiblings);
        sb.append(fieldName(f)).append(" = value.getNumber(); ").append(hasFlagName(f))
            .append(" = true; return this; }\n");
        sb.append(indent).append("public Builder set").append(capName).append("Value(int value) { ");
        if (oneofSiblings != null) writeOneofSiblingClears(sb, f, oneofSiblings);
        sb.append(fieldName(f)).append(" = value; ").append(hasFlagName(f))
            .append(" = true; return this; }\n");
      } else {
        sb.append(indent).append("public ").append(primJavaType(f)).append(" get").append(capName)
            .append("() { return ").append(fieldName(f)).append("; }\n");
        sb.append(indent).append("public Builder set").append(capName).append("(").append(primJavaType(f))
            .append(" value) {");
        if (k == FieldKind.SCALAR_STRING || k == FieldKind.SCALAR_BYTES || k == FieldKind.MESSAGE) {
          sb.append(" if (value == null) throw new NullPointerException();");
        }
        sb.append(" ");
        if (oneofSiblings != null) writeOneofSiblingClears(sb, f, oneofSiblings);
        sb.append(fieldName(f)).append(" = value; ").append(hasFlagName(f))
            .append(" = true; return this; }\n");
      }
      sb.append(indent).append("public Builder clear").append(capName).append("() { ").append(hasFlagName(f))
          .append(" = false; ").append(fieldName(f)).append(" = ").append(defaultValue(f))
          .append("; return this; }\n");
    }
  }

  // --- writeTo / getSerializedSize / mergeFrom snippets -------------------

  private void writeFieldWrite(StringBuilder sb, FieldDescriptorProto f, String indent) {
    int n = f.getNumber();
    String name = fieldName(f);
    if (f.getLabel() == Label.LABEL_REPEATED) {
      sb.append(indent).append("for (int i = 0; i < ").append(name).append(".size(); i++) {\n");
      sb.append(indent).append("  output.").append(writeMethod(f)).append("(").append(n)
          .append(", ").append(name).append(".get(i));\n");
      sb.append(indent).append("}\n");
    } else {
      sb.append(indent).append("if (").append(hasFlagName(f)).append(") output.")
          .append(writeMethod(f)).append("(").append(n).append(", ").append(name)
          .append(");\n");
    }
  }

  private void writeFieldSize(StringBuilder sb, FieldDescriptorProto f, String indent) {
    int n = f.getNumber();
    String name = fieldName(f);
    if (f.getLabel() == Label.LABEL_REPEATED) {
      sb.append(indent).append("for (int i = 0; i < ").append(name).append(".size(); i++) {\n");
      sb.append(indent).append("  size += CodedOutputStream.").append(sizeMethod(f)).append("(").append(n)
          .append(", ").append(name).append(".get(i));\n");
      sb.append(indent).append("}\n");
    } else {
      sb.append(indent).append("if (").append(hasFlagName(f)).append(") size += CodedOutputStream.")
          .append(sizeMethod(f)).append("(").append(n).append(", ").append(name)
          .append(");\n");
    }
  }

  private void writeFieldEquals(StringBuilder sb, FieldDescriptorProto f, String indent) {
    String fld = fieldName(f);
    String hf = hasFlagName(f);
    if (f.getLabel() == Label.LABEL_REPEATED) {
      // List equality compares element-by-element regardless of List subclass.
      sb.append(indent).append("if (!").append(fld).append(".equals(other.").append(fld).append(")) return false;\n");
    } else {
      sb.append(indent).append("if (").append(hf).append(" != other.").append(hf).append(") return false;\n");
      sb.append(indent).append("if (").append(hf).append(" && !(").append(equalityCompare(f, fld, "other." + fld))
          .append(")) return false;\n");
    }
  }

  private void writeFieldHash(StringBuilder sb, FieldDescriptorProto f, String indent) {
    String fld = fieldName(f);
    String hf = hasFlagName(f);
    if (f.getLabel() == Label.LABEL_REPEATED) {
      // Empty list contributes nothing — keeps hash consistent between an
      // unset repeated and a cleared one.
      sb.append(indent).append("if (!").append(fld).append(".isEmpty()) hash = hash * 37 + ").append(fld).append(".hashCode();\n");
    } else {
      sb.append(indent).append("if (").append(hf).append(") hash = hash * 37 + ").append(hashContribution(f, fld)).append(";\n");
    }
  }

  /** Snippet that's true when two field values of this type are equal. Used inside
   *  generated {@code equals(Object)}. Floating point uses bit-equality so NaN
   *  compares as equal to itself, matching javalite. */
  private String equalityCompare(FieldDescriptorProto f, String a, String b) {
    switch (FieldKind.from(f.getType())) {
      case SCALAR_INT32: case SCALAR_UINT32: case SCALAR_SINT32:
      case SCALAR_FIXED32: case SCALAR_SFIXED32: case ENUM:
      case SCALAR_INT64: case SCALAR_UINT64: case SCALAR_SINT64:
      case SCALAR_FIXED64: case SCALAR_SFIXED64:
      case SCALAR_BOOL:
        return a + " == " + b;
      case SCALAR_FLOAT:
        return "Float.floatToIntBits(" + a + ") == Float.floatToIntBits(" + b + ")";
      case SCALAR_DOUBLE:
        return "Double.doubleToLongBits(" + a + ") == Double.doubleToLongBits(" + b + ")";
      case SCALAR_STRING: case SCALAR_BYTES: case MESSAGE:
        return a + ".equals(" + b + ")";
      default: throw new IllegalStateException();
    }
  }

  /** Hash contribution for one field. Caller decides whether to include it
   *  (gated by has-flag for non-repeated, by non-emptiness for repeated). */
  private String hashContribution(FieldDescriptorProto f, String name) {
    switch (FieldKind.from(f.getType())) {
      case SCALAR_INT32: case SCALAR_UINT32: case SCALAR_SINT32:
      case SCALAR_FIXED32: case SCALAR_SFIXED32: case ENUM:
        return name; // int's hashCode is the int itself
      case SCALAR_INT64: case SCALAR_UINT64: case SCALAR_SINT64:
      case SCALAR_FIXED64: case SCALAR_SFIXED64:
        return "(int) (" + name + " ^ (" + name + " >>> 32))";
      case SCALAR_FLOAT:
        return "Float.floatToIntBits(" + name + ")";
      case SCALAR_DOUBLE:
        return "(int) (Double.doubleToLongBits(" + name + ") ^ (Double.doubleToLongBits(" + name + ") >>> 32))";
      case SCALAR_BOOL:
        return "(" + name + " ? 1231 : 1237)";
      case SCALAR_STRING: case SCALAR_BYTES: case MESSAGE:
        return name + ".hashCode()";
      default: throw new IllegalStateException();
    }
  }

  private void writeFieldToString(StringBuilder sb, FieldDescriptorProto f, String indent) {
    String fld = fieldName(f);
    String hf = hasFlagName(f);
    String wireName = f.getName(); // proto-side name (camelCase as declared)
    String capName = capitalize(wireName);
    FieldKind kind = FieldKind.from(f.getType());

    if (f.getLabel() == Label.LABEL_REPEATED) {
      sb.append(indent).append("if (!").append(fld).append(".isEmpty()) {\n");
      sb.append(indent).append("  sb.append(sep).append(\"").append(wireName).append("=\").append(");
      if (kind == FieldKind.ENUM) {
        // Render typed enum names (the storage is List<Integer>; getXxxList()
        // returns List<EnumType>).
        sb.append("get").append(capName).append("List()");
      } else {
        sb.append(fld);
      }
      sb.append(");\n");
      sb.append(indent).append("  sep = \", \";\n");
      sb.append(indent).append("}\n");
    } else {
      sb.append(indent).append("if (").append(hf).append(") {\n");
      sb.append(indent).append("  sb.append(sep).append(\"").append(wireName).append("=\")");
      if (kind == FieldKind.SCALAR_STRING) {
        sb.append(".append('\"').append(").append(fld).append(").append('\"')");
      } else if (kind == FieldKind.ENUM) {
        // Render typed enum (or null for unknown numeric values).
        sb.append(".append(get").append(capName).append("())");
      } else {
        sb.append(".append(").append(fld).append(")");
      }
      sb.append(";\n");
      sb.append(indent).append("  sep = \", \";\n");
      sb.append(indent).append("}\n");
    }
  }

  private void writeFieldRead(StringBuilder sb, FieldDescriptorProto f, String indent) {
    int wireType = wireType(f);
    int tag = (f.getNumber() << 3) | wireType;
    String name = fieldName(f);
    String capName = capitalize(f.getName());
    sb.append(indent).append("case ").append(tag).append(": {\n");
    if (f.getLabel() == Label.LABEL_REPEATED) {
      if (FieldKind.from(f.getType()) == FieldKind.MESSAGE) {
        String typeRef = registry.javaName(f.getTypeName());
        sb.append(indent).append("  ensure").append(capName).append("Mutable();\n");
        sb.append(indent).append("  ").append(typeRef).append(".Builder b = ").append(typeRef).append(".newBuilder();\n");
        sb.append(indent).append("  input.readMessage(b);\n");
        sb.append(indent).append("  ").append(name).append(".add(b.buildPartial());\n");
      } else {
        sb.append(indent).append("  ensure").append(capName).append("Mutable();\n");
        sb.append(indent).append("  ").append(name).append(".add(input.").append(readMethod(f)).append("());\n");
      }
    } else if (FieldKind.from(f.getType()) == FieldKind.MESSAGE) {
      String typeRef = registry.javaName(f.getTypeName());
      sb.append(indent).append("  ").append(typeRef).append(".Builder b = ").append(typeRef).append(".newBuilder();\n");
      sb.append(indent).append("  input.readMessage(b);\n");
      sb.append(indent).append("  ").append(name).append(" = b.buildPartial();\n");
      sb.append(indent).append("  ").append(hasFlagName(f)).append(" = true;\n");
    } else {
      sb.append(indent).append("  ").append(name).append(" = input.").append(readMethod(f)).append("();\n");
      sb.append(indent).append("  ").append(hasFlagName(f)).append(" = true;\n");
    }
    sb.append(indent).append("  break;\n");
    sb.append(indent).append("}\n");
  }

  // --- type / method-name lookup tables ----------------------------------

  private String primJavaType(FieldDescriptorProto f) {
    switch (FieldKind.from(f.getType())) {
      case SCALAR_INT32: case SCALAR_UINT32: case SCALAR_SINT32:
      case SCALAR_FIXED32: case SCALAR_SFIXED32: case ENUM:
        return "int";
      case SCALAR_INT64: case SCALAR_UINT64: case SCALAR_SINT64:
      case SCALAR_FIXED64: case SCALAR_SFIXED64:
        return "long";
      case SCALAR_FLOAT: return "float";
      case SCALAR_DOUBLE: return "double";
      case SCALAR_BOOL: return "boolean";
      case SCALAR_STRING: return "String";
      case SCALAR_BYTES: return "ByteString";
      case MESSAGE: return registry.javaName(f.getTypeName());
      default: throw new IllegalStateException();
    }
  }

  /** Element type used for {@code List<T>} fields. Enums are stored as
   *  {@code Integer} so that {@code input.readEnum()} (which returns {@code int})
   *  drops in directly without bridging through the typed enum class. */
  private String repeatedStorageType(FieldDescriptorProto f) {
    if (FieldKind.from(f.getType()) == FieldKind.ENUM) return "Integer";
    return boxedJavaType(f);
  }

  /** The boxed equivalent — needed for {@code List<T>} declarations and for
   *  the typed-enum API on enum fields (where the underlying storage is int). */
  private String boxedJavaType(FieldDescriptorProto f) {
    switch (FieldKind.from(f.getType())) {
      case SCALAR_INT32: case SCALAR_UINT32: case SCALAR_SINT32:
      case SCALAR_FIXED32: case SCALAR_SFIXED32:
        return "Integer";
      case SCALAR_INT64: case SCALAR_UINT64: case SCALAR_SINT64:
      case SCALAR_FIXED64: case SCALAR_SFIXED64:
        return "Long";
      case SCALAR_FLOAT: return "Float";
      case SCALAR_DOUBLE: return "Double";
      case SCALAR_BOOL: return "Boolean";
      case SCALAR_STRING: return "String";
      case SCALAR_BYTES: return "ByteString";
      case ENUM: return registry.javaName(f.getTypeName());
      case MESSAGE: return registry.javaName(f.getTypeName());
      default: throw new IllegalStateException();
    }
  }

  private String defaultValue(FieldDescriptorProto f) {
    switch (FieldKind.from(f.getType())) {
      case SCALAR_INT32: case SCALAR_UINT32: case SCALAR_SINT32:
      case SCALAR_FIXED32: case SCALAR_SFIXED32: case ENUM:
        return "0";
      case SCALAR_INT64: case SCALAR_UINT64: case SCALAR_SINT64:
      case SCALAR_FIXED64: case SCALAR_SFIXED64:
        return "0L";
      case SCALAR_FLOAT: return "0F";
      case SCALAR_DOUBLE: return "0D";
      case SCALAR_BOOL: return "false";
      case SCALAR_STRING: return "\"\"";
      case SCALAR_BYTES: return "ByteString.EMPTY";
      case MESSAGE: return "null";
      default: throw new IllegalStateException();
    }
  }

  private String initializerSuffix(FieldDescriptorProto f) {
    switch (FieldKind.from(f.getType())) {
      case SCALAR_STRING: return " = \"\"";
      case SCALAR_BYTES: return " = ByteString.EMPTY";
      default: return "";
    }
  }

  private int wireType(FieldDescriptorProto f) {
    if (f.getLabel() == Label.LABEL_REPEATED && FieldKind.from(f.getType()) == FieldKind.MESSAGE) {
      return 2; // length-delimited
    }
    switch (FieldKind.from(f.getType())) {
      case SCALAR_INT32: case SCALAR_INT64: case SCALAR_UINT32: case SCALAR_UINT64:
      case SCALAR_SINT32: case SCALAR_SINT64: case SCALAR_BOOL: case ENUM:
        return 0; // varint
      case SCALAR_FIXED64: case SCALAR_SFIXED64: case SCALAR_DOUBLE:
        return 1; // 64-bit
      case SCALAR_STRING: case SCALAR_BYTES: case MESSAGE:
        return 2; // length-delimited
      case SCALAR_FIXED32: case SCALAR_SFIXED32: case SCALAR_FLOAT:
        return 5; // 32-bit
      default: throw new IllegalStateException();
    }
  }

  private String writeMethod(FieldDescriptorProto f) {
    switch (FieldKind.from(f.getType())) {
      case SCALAR_INT32: return "writeInt32";
      case SCALAR_INT64: return "writeInt64";
      case SCALAR_UINT32: return "writeUInt32";
      case SCALAR_UINT64: return "writeUInt64";
      case SCALAR_SINT32: return "writeSInt32";
      case SCALAR_SINT64: return "writeSInt64";
      case SCALAR_FIXED32: return "writeFixed32";
      case SCALAR_FIXED64: return "writeFixed64";
      case SCALAR_SFIXED32: return "writeSFixed32";
      case SCALAR_SFIXED64: return "writeSFixed64";
      case SCALAR_FLOAT: return "writeFloat";
      case SCALAR_DOUBLE: return "writeDouble";
      case SCALAR_BOOL: return "writeBool";
      case SCALAR_STRING: return "writeString";
      case SCALAR_BYTES: return "writeBytes";
      case ENUM: return "writeEnum";
      case MESSAGE: return "writeMessage";
      default: throw new IllegalStateException();
    }
  }

  private String sizeMethod(FieldDescriptorProto f) {
    switch (FieldKind.from(f.getType())) {
      case SCALAR_INT32: return "computeInt32Size";
      case SCALAR_INT64: return "computeInt64Size";
      case SCALAR_UINT32: return "computeUInt32Size";
      case SCALAR_UINT64: return "computeUInt64Size";
      case SCALAR_SINT32: return "computeSInt32Size";
      case SCALAR_SINT64: return "computeSInt64Size";
      case SCALAR_FIXED32: return "computeFixed32Size";
      case SCALAR_FIXED64: return "computeFixed64Size";
      case SCALAR_SFIXED32: return "computeSFixed32Size";
      case SCALAR_SFIXED64: return "computeSFixed64Size";
      case SCALAR_FLOAT: return "computeFloatSize";
      case SCALAR_DOUBLE: return "computeDoubleSize";
      case SCALAR_BOOL: return "computeBoolSize";
      case SCALAR_STRING: return "computeStringSize";
      case SCALAR_BYTES: return "computeBytesSize";
      case ENUM: return "computeEnumSize";
      case MESSAGE: return "computeMessageSize";
      default: throw new IllegalStateException();
    }
  }

  private String readMethod(FieldDescriptorProto f) {
    switch (FieldKind.from(f.getType())) {
      case SCALAR_INT32: return "readInt32";
      case SCALAR_INT64: return "readInt64";
      case SCALAR_UINT32: return "readUInt32";
      case SCALAR_UINT64: return "readUInt64";
      case SCALAR_SINT32: return "readSInt32";
      case SCALAR_SINT64: return "readSInt64";
      case SCALAR_FIXED32: return "readFixed32";
      case SCALAR_FIXED64: return "readFixed64";
      case SCALAR_SFIXED32: return "readSFixed32";
      case SCALAR_SFIXED64: return "readSFixed64";
      case SCALAR_FLOAT: return "readFloat";
      case SCALAR_DOUBLE: return "readDouble";
      case SCALAR_BOOL: return "readBool";
      case SCALAR_STRING: return "readString";
      case SCALAR_BYTES: return "readBytes";
      case ENUM: return "readEnum";
      default: throw new IllegalStateException("read for " + f.getType() + " uses readMessage path");
    }
  }

  // --- naming -------------------------------------------------------------

  private static String fieldName(FieldDescriptorProto f) {
    return f.getName() + "_";
  }

  private static String hasFlagName(FieldDescriptorProto f) {
    return "has_" + f.getName() + "_";
  }

  private static String capitalize(String s) {
    if (s.isEmpty()) return s;
    return Character.toUpperCase(s.charAt(0)) + s.substring(1);
  }
}
